name: Node.js Package

# Trigger the workflow when a new release is created
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up Node.js (version 20)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - run: npm ci

      # Run tests
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up Node.js and configure npm registry
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # Install dependencies
      - run: npm ci

      # Publish the package to npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}  # Use the npm token from GitHub secrets
